### ISSUE TITLE
Very useful, but doesn't work in Xcode 6.3 any more

### ISSUE THREAD

**Issue by billdavid** [insanehunter/XCode4_beginning_of_line#36]
I think it works pretty well in Xcode 4 to XCode 6.2. But since I upgrade to Xcode 6.3 several days ago, it doesn't work any more. What a pity. Could you please have a look. I can't live without it. I hate the stupid default behavior in Xcode.

**Comment by insanehunter** [comment]
Please try downloading and rebuilding it - every Xcode release requires a compatibility GUID line in Info.plust, otherwise it won't load the plugin.

**Comment by billdavid** [comment]
Great. It works well after downloading the latest code. Thanks a lot.
